import { NextResponse } from "next/server";
import { getSessionUserId } from "@/lib/auth/session";
import { canWrite } from "@/lib/permissions";
import { supabaseRequest } from "@/lib/supabase/server";
import { resolveActiveOrganization } from "@/services/organization-service";

const resources = ["projects","tasks","customers","leads","meetings","documents","support_requests"] as const;
type Resource = typeof resources[number];
function isResource(value:string): value is Resource { return resources.includes(value as Resource); }
async function context(resource:string) { if(!isResource(resource)) throw new Error("Unknown resource"); const userId=await getSessionUserId(); if(!userId) throw new Error("Unauthenticated"); const workspace=await resolveActiveOrganization(userId); return { resource, userId, workspace }; }
function message(error:unknown) { return error instanceof Error && error.message === "Unauthenticated" ? "Your session has expired." : "Unable to complete that request."; }
export async function GET(_:Request,{params}:{params:Promise<{resource:string}>}) { try { const {resource,workspace}=await context((await params).resource); const data=await supabaseRequest<Record<string,unknown>[]>(`${resource}?organization_id=eq.${workspace.organization.id}&select=*&order=created_at.desc`); return NextResponse.json({data,workspace:{name:workspace.organization.name,role:workspace.role}}); } catch(error) { return NextResponse.json({message:message(error)},{status:401}); } }
export async function POST(request:Request,{params}:{params:Promise<{resource:string}>}) { try { const {resource,userId,workspace}=await context((await params).resource); if(!canWrite(workspace.role)) return NextResponse.json({message:"Your role is read-only."},{status:403}); const values=await request.json() as Record<string,unknown>; const data=await supabaseRequest<Record<string,unknown>[]>(resource,{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({...values,organization_id:workspace.organization.id,created_by:userId})}); return NextResponse.json({data:data[0]},{status:201}); } catch(error) { return NextResponse.json({message:message(error)},{status:400}); } }
export async function PATCH(request:Request,{params}:{params:Promise<{resource:string}>}) { try { const {resource,workspace}=await context((await params).resource); if(!canWrite(workspace.role)) return NextResponse.json({message:"Your role is read-only."},{status:403}); const {id,...values}=await request.json() as {id:string}&Record<string,unknown>; const data=await supabaseRequest<Record<string,unknown>[]>(`${resource}?id=eq.${encodeURIComponent(id)}&organization_id=eq.${workspace.organization.id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(values)}); return NextResponse.json({data:data[0]}); } catch(error) { return NextResponse.json({message:message(error)},{status:400}); } }
export async function DELETE(request:Request,{params}:{params:Promise<{resource:string}>}) { try { const {resource,workspace}=await context((await params).resource); if(!canWrite(workspace.role)) return NextResponse.json({message:"Your role is read-only."},{status:403}); const id=new URL(request.url).searchParams.get("id"); if(!id) return NextResponse.json({message:"Record required."},{status:400}); await supabaseRequest(`${resource}?id=eq.${encodeURIComponent(id)}&organization_id=eq.${workspace.organization.id}`,{method:"DELETE"}); return new NextResponse(null,{status:204}); } catch(error) { return NextResponse.json({message:message(error)},{status:400}); } }
