"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type RecordItem={id:string;name?:string;title?:string;subject?:string;status?:string;stage?:string;created_at:string};
type Props={module:"projects"|"tasks"|"customers"|"leads"|"meetings"|"documents"|"support_requests"; title:string; singular:string};
export function WorkspaceModulePage({module,title,singular}:Props){
 const [items,setItems]=useState<RecordItem[]|null>(null),[query,setQuery]=useState(""),[value,setValue]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const field=module==="tasks"||module==="meetings"||module==="documents"?"title":module==="support_requests"?"subject":"name";
 const load=useCallback(async(search="")=>{setError("");try{const r=await fetch(`/api/workspace/${module}?limit=100&search=${encodeURIComponent(search)}`);const b=await r.json();if(!r.ok)throw Error(b.message);setItems(b.data)}catch(e){setError(e instanceof Error?e.message:"Unable to load records.")}},[module]);
 useEffect(()=>{ const timer=window.setTimeout(()=>{void load()},0); return ()=>window.clearTimeout(timer); },[load]);
 async function create(e:React.FormEvent){e.preventDefault();if(!value.trim())return;setSaving(true);setError("");try{const r=await fetch(`/api/workspace/${module}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({[field]:value.trim()})});const b=await r.json();if(!r.ok)throw Error(b.message);setValue("");await load(query)}catch(e){setError(e instanceof Error?e.message:"Unable to create record.")}finally{setSaving(false)}}
 async function remove(id:string){if(!confirm(`Delete this ${singular.toLowerCase()}?`))return;try{const r=await fetch(`/api/workspace/${module}?id=${id}`,{method:"DELETE"});if(!r.ok){const b=await r.json();throw Error(b.message)}setItems(v=>v?.filter(x=>x.id!==id)??null)}catch(e){setError(e instanceof Error?e.message:"Unable to delete record.")}}
 return <main className="app"><section className="content"><header className="topbar"><div className="crumb"><Link href="/app">Workspace</Link><b>/</b><strong>{title}</strong></div><a className="assistant-button" href="/app/assistant">✦ Ask AI</a></header><div className="page"><section className="intro"><div><p className="eyebrow">LIVE WORKSPACE DATA</p><h1>{title}</h1><p>Records are scoped to your active workspace.</p></div></section><section className="card project-card"><div className="card-heading"><h2>Create {singular}</h2></div><form className="inline-form" onSubmit={create}><input aria-label={`${singular} name`} value={value} onChange={e=>setValue(e.target.value)} placeholder={`${singular} ${field}`} required/><button className="primary-button" disabled={saving}>{saving?"Saving…":`Create ${singular}`}</button></form>{error&&<p className="form-error" role="alert">{error}</p>}<div className="module-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void load(query)}} placeholder={`Search ${title.toLowerCase()}`}/><button className="ghost-button" onClick={()=>void load(query)}>Search</button></div>{items===null?<p>Loading records…</p>:items.length===0?<div className="empty-state"><b>No {title.toLowerCase()} yet.</b><p>Create the first {singular.toLowerCase()} for this workspace.</p></div>:<div className="project-list">{items.map(item=><article className="project-row" key={item.id}><div className="project-symbol violet">{(item.name??item.title??item.subject??"?").slice(0,1).toUpperCase()}</div><div className="project-copy"><h3>{item.name??item.title??item.subject}</h3><p>{item.status??item.stage??"New"} · {new Date(item.created_at).toLocaleDateString()}</p></div><button className="text-button delete-button" onClick={()=>void remove(item.id)}>Delete</button></article>)}</div>}</section></div></section></main>;
}
