import { NextRequest, NextResponse } from "next/server";
import { getSessionUserId } from "@/lib/auth/session";
import { demoWorkspaceId, isDemoMode } from "@/lib/demo";
import { can, type Permission } from "@/lib/permissions";
import { supabaseRequest } from "@/lib/supabase/server";
import { resolveActiveOrganization } from "@/services/organization-service";
import { workspaceModules, type WorkspaceModule } from "@/lib/workspace/types";
const permissions:Record<WorkspaceModule,Permission>={projects:"project.create",tasks:"task.create",customers:"record.write",leads:"record.write",meetings:"record.write"}; const required:Record<WorkspaceModule,string[]>={projects:["name"],tasks:["title"],customers:["name"],leads:["name"],meetings:["title"]};
function entity(value:string){return workspaceModules.includes(value as WorkspaceModule)?value as WorkspaceModule:null} function fail(message:string,status:number){return NextResponse.json({message},{status})}
async function context(module:string,write=false){const table=entity(module);if(!table)return null;if(isDemoMode)return {table,workspaceId:demoWorkspaceId,key:"workspace_id",userId:null};const userId=await getSessionUserId();if(!userId)throw Error("UNAUTHORIZED");const workspace=await resolveActiveOrganization(userId);if(write&&!can(workspace.role,permissions[table]))throw Error("FORBIDDEN");return {table,workspaceId:workspace.organization.id,key:"organization_id",userId};}
export async function GET(_:NextRequest,{params}:{params:Promise<{module:string}>}){try{const found=await context((await params).module);if(!found)return fail("Unknown module",404);return NextResponse.json({data:await supabaseRequest<unknown[]>(`${found.table}?${found.key}=eq.${found.workspaceId}&order=created_at.desc`),demo:isDemoMode});}catch(cause){if(cause instanceof Error&&cause.message==="UNAUTHORIZED")return fail("Sign in to load workspace records.",401);if(process.env.NODE_ENV==="development")console.error("Workspace records failed",cause);return fail("Unable to load workspace records.",500)}}
export async function POST(request:NextRequest,{params}:{params:Promise<{module:string}>}){try{const found=await context((await params).module,true);if(!found)return fail("Unknown module",404);const input=await request.json() as Record<string,unknown>;if(required[found.table].some(k=>typeof input[k]!=="string"||!String(input[k]).trim()))return fail(`A ${required[found.table][0]} is required.`,400);const payload={...input,[found.key]:found.workspaceId,...(found.userId?{created_by:found.userId}:{})};const data=await supabaseRequest<unknown[]>(found.table,{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)});return NextResponse.json({data:data[0]},{status:201});}catch(cause){if(cause instanceof Error&&cause.message==="UNAUTHORIZED")return fail("Sign in to manage workspace records.",401);return fail("Unable to create record.",403)}}
