-- First functional Opervia slice: workspace-scoped delivery and CRM records.
alter type public.organization_role add value if not exists 'client';
alter table public.projects add column if not exists client text, add column if not exists description text, add column if not exists start_date date, add column if not exists due_date date, add column if not exists budget numeric(12,2), add column if not exists progress integer not null default 0 check (progress between 0 and 100), add column if not exists priority text not null default 'medium', add column if not exists archived_at timestamptz;
alter table public.tasks add column if not exists assignee_id uuid references auth.users(id) on delete set null, add column if not exists due_date timestamptz, add column if not exists priority text not null default 'medium', add column if not exists description text, add column if not exists labels text[] not null default '{}', add column if not exists completed_at timestamptz;
alter table public.customers add column if not exists email text, add column if not exists phone text, add column if not exists tags text[] not null default '{}', add column if not exists notes text, add column if not exists assigned_owner_id uuid references auth.users(id) on delete set null;
alter table public.leads add column if not exists company text, add column if not exists email text, add column if not exists phone text, add column if not exists source text, add column if not exists notes text, add column if not exists assigned_owner_id uuid references auth.users(id) on delete set null, add column if not exists estimated_value numeric(12,2), add column if not exists follow_up_date date, add column if not exists tags text[] not null default '{}';
create index if not exists projects_organization_created_idx on public.projects(organization_id, created_at desc);
create index if not exists tasks_organization_due_idx on public.tasks(organization_id, due_date);
create index if not exists leads_organization_stage_idx on public.leads(organization_id, stage);

alter table public.meetings add column if not exists attendees text[] not null default '{}', add column if not exists customer_id uuid references public.customers(id) on delete set null, add column if not exists project_id uuid references public.projects(id) on delete set null, add column if not exists meeting_link text, add column if not exists agenda text;
